### ISSUE TITLE
Workshop location: Cologne

### ISSUE THREAD

**Issue by badboy** [rust-community/novemb.rs#1]
# Take part in the european code sprint

the [Rust User Group Cologne](http://rust.cologne/) will take part. We're currently figuring out the venue.

**Comment by killercup** [comment]
We are currently discussing this here: https://github.com/Rustaceans/rust-cologne/issues/14

**Comment by skade** [comment]
I added you without a link.

**Comment by badboy** [comment]
Perfect. We add a location once we have one.

**Comment by killercup** [comment]
Okay, the location is the C4 (as always; already on the website).

People can find more information about our event [here](http://www.meetup.com/RustCologne/events/235374218/) and [here](http://rust.cologne/2016/11/19/novemb-rs.html).
