### ISSUE TITLE
Workshop location: Etsy in Brooklyn, NY

### ISSUE THREAD

**Issue by jedahan** [rust-community/novemb.rs#14]
# Take part in the european code sprint

Started a rust interest group @[Etsy](etsy.com). The office is in DUMBO, brooklyn, NY, USA. We would totally host some people here.

**Comment by steveklabnik** [comment]
Oh this would be great!

**Comment by jfo** [comment]
👐

**Comment by frewsxcv** [comment]
Someone on reddit offered their Manhattan office for novemb.rs as well. I reached out to them via email and they apparently just need to confirm internally that the space is open for that weekend. I don't know what the capacity is; I'll share this thread with them. My conversation with them happened independently of this thread, so I'm glad to see such passionate Rustaceans in NYC :)

**Comment by ysimonson** [comment]
That's me! We could likely offer The Muse's office as well, which could hold up to ~150 people if we spread out across the office. But I'd guess Etsy's more well-prepared to handle this, and given the tight deadline, it probably makes more sense for them to host.

**Comment by skade** [comment]
Well, most of the work is keeping the doors open and make sure people get food in some way (maybe by helping with bulk orders), so maybe it would be best to just make sure you join forces and everyone solves a little of that.

**Comment by jedahan** [comment]
Yeah I am trying to push past our 'hey please give a 4 weeks heads up for weekend events' policy, will hear back tomorrow morning with whether or not we can make this go through or not.

**Comment by jedahan** [comment]
Status update: looks like we can host about 20 people. I will be creating an eventbrite and/or indieweb event soon, which I will post here, that will be open for registration in 2 waves of 10 spots to make it a bit more fair. I still think having a second spot in Manhattan @The Muse would be good, I really am not sure what the turnout will be for this.

**Comment by alevy** [comment]
+1

**Comment by jedahan** [comment]
The eventbrite is https://novembrsetsy.eventbrite.com

The first wave of tickets should open up at noon tomorrow.

This is my first eventbrite so I might have made a mistake, and of course suggestions are appreciated.

**Comment by frewsxcv** [comment]
@jedahan FYI, it looks like I can register for "First Wave" _and_ "Second Wave" right now. Not sure if that was intendend

**Comment by jedahan** [comment]
Thanks for the heads up, fixing

**Comment by jedahan** [comment]
Second wave should be hidden now

**Comment by frewsxcv** [comment]
@jedahan If there are still spots available, I can create an event on the Rust NYC page advertising it if that's something you'd find helpful.

**Comment by frewsxcv** [comment]
.....or possible just send a message to the meetup group in general, without an event.

**Comment by jedahan** [comment]
Yeah that would be great! I think there are a few available and I will open up more on Friday

**Comment by badboy** [comment]
Added a note about the tickets.
