### ISSUE TITLE
Workshop location: Vilnius, Lithuania

### ISSUE THREAD

**Issue by d-unsed** [rust-community/novemb.rs#16]
Hi there!

We would like to join novemb.rs in Vilnius, Lithuania.

There are some general questions:

 - Agenda. Will there be a plan that is recommended to follow during the event?
 
 - Newcomers. Are there any preferences on how to involve newcomers in the hacking?
   Especially if there is a high ratio of `beginners / experienced` rust developers, maybe you can recommend what to do in this case?

 - Presentations. Do presentations fit into the format of the event? We'd like to combine novemb.rs and
   the first [Rust Vilnius](https://www.meetup.com/Rust-in-Vilnius/) meetup.
   Thus, it would be nice to have a short intro to Rust language, its ecosystem, community etc
   (up to 1 hour).
 
 - Swags 😄  Will it be possible to get some Rust stickers for participants?

 Thank you!

 /cc @Nercury

**Comment by badboy** [comment]
Agenda: there won't be a fixed agenda. The weekend should be used to hack and collaborate on Rust projects on your own pace.

Newcomers: It would be nice to have some material ready (more or less point newcomers to tutorials) and offer help/mentorship as best as possible (often it is enough to talk to people while they are trying out things)

Presentations: again, we won't dictate any agenda. If you want to fit in presentations for your audience, that's definitely a good way to get started.

Swags: I can ask if there's any budget for that or if anyone is willing to send over some of their own (I don't have enough stickers at the moment to send them)

**Comment by skade** [comment]
@d-unseductable please get in touch with me (flo@andersground.net) for details about possible help with swag and catering.

Agenda: hop on IRC, ask for help ;). We won't dictate a local one. If you need someone to do a remote talk about a specific interest of you, please get in touch, we'll see what we can do.

\o/ first meetup!

**Comment by skade** [comment]
Hi, I added you to the location list and posted your meetup.

**Comment by d-unsed** [comment]
Oh thanks! I just wanted to submit a PR for that :)

Thanks for the answers. @skade, I'll write you an email next week, once we know an approximate number of participants.

**Comment by badboy** [comment]
Was added in 3a493e79a540d675ff952d13a0088c1f006d7821.
If you need any more info, feel free to open an issue or re-open this one.
