### ISSUE TITLE
Project & Mentorship: SUPER Android Analyzer

### ISSUE THREAD

**Issue by Razican** [rust-community/novemb.rs#17]
[SUPER](https://github.com/SUPERAndroidAnalyzer/super) would like to participate in novemb.rs by offering mentorship to our project and creating some issues to be solved in the hackaton. The mentors would be me (@Razican) and Bruno (@Br1oP).

I guess we would need to be in the IRC too, where can we find information on how to register etc? (we are not users of IRC). Any extra information you need, feel free to ask.

**Comment by badboy** [comment]
Hey and welcome.
To hop onto IRC you don't _need_ to register. Pick an IRC client (either a native one or a web-based one like [IRCCloud](https://www.irccloud.com/) or [Mibbit](https://www.mibbit.com/)) and connect to `irc.mozilla.org`.
Then you can join the `#rust` channel or [any of the other dozens](https://www.rust-lang.org/en-US/community.html#irc-channels).

We will likely have a separate channel for novemb.rs, not sure which one yet.
Please also add your project and you as mentors to this site (simply send us a PR).

**Comment by badboy** [comment]
Information is on the site now. If you need any more info, feel free to re-open or open new issues.
