### ISSUE TITLE
Workshop location: Tübingen Germany

### ISSUE THREAD

**Issue by willi-kappler** [rust-community/novemb.rs#18]
Hi everyone,

we can provice space (with beamer + wireless) at my university in Tübingen.

I can also help out new people interested in Rust.

**Comment by badboy** [comment]
That's definitely great! If that happens, please add yourself to the location list.

**Comment by skade** [comment]
\o/

We'd need a location (or a link to the place) to send people to :)

**Comment by willi-kappler** [comment]
Here we go:

Hölderlinstraße 12
72074 Tübingen

http://www.openstreetmap.org/?mlat=48.52645&mlon=9.05974#map=19/48.52645/9.05974

Room: 227, first floor (Erdgeschoss), there will be signs nearby the entrance with a Rust logo.

I'll also try to provide some snacks and drinks.

**Comment by badboy** [comment]
Added in #26

**Comment by skade** [comment]
@willi-kappler can you add a time to events.yml? Use the "more" field.
