### ISSUE TITLE
Communication channels

### ISSUE THREAD

**Issue by skade** [rust-community/novemb.rs#19]
We need to set up and document communication channels.

IRC is great, but also maybe slack and especially some form of video calling.

**Comment by badboy** [comment]
`#novemb.rs` on irc.mozilla.org

**Comment by erickt** [comment]
@brson / @aturon: is this something the community could use vidyo for?

Or maybe it'd be better to just setup a google hangouts. I think it still can handle 10-20 participants.

**Comment by skade** [comment]
There's now a list of online venues on the page.

It might be worthwhile to figure out a way how people can find others to set up their video channel with.

**Comment by aturon** [comment]
@erickt I suspect that hangouts is going to be much easier to get people signed up for -- we frequently have problems bringing people onto vidyo.
