### ISSUE TITLE
Mentorship: Rust on Cortex-M microcontrollers

### ISSUE THREAD

**Issue by japaric** [rust-community/novemb.rs#20]
I've two documentation/tutorial projects on this topic:

- [rust-discovery][1]. Ideal for beginners (That have no previous experience with "embedded stuff"). Walkthrough style tutorial. Requires an STM32F3DISCOVERY board to be able to follow the material though.

- [copper][2]. Device-agnostic documentation. More focused on low level details. Aimed at people that has previous experience with microcontrollers.

[1]: https://japaric.github.io/rust-discovery/
[2]: http://japaric.github.io/copper/

Will be on IRC during the event and I'd be happy to answer any questions about that material or general questions about Cortex-M microcontrollers.

Name: Jorge Aparicio
IRC: japaric (\*)

(\*) I own the #rust-embedded channel on Mozilla's network which is the perfect place to ask questions about this topic. I can join any other novemb.rs specific IRC channel as well.

**Comment by skade** [comment]
Added you to the mentors list.

**Comment by japaric** [comment]
I guess I can close this now.
