### ISSUE TITLE
Workshop location: Seattle

### ISSUE THREAD

**Issue by carols10cents** [rust-community/novemb.rs#22]
@eeyun, with Chef/Habitat, is going to be in Seattle that weekend and is interested in potentially hosting a PST spot! Does he need to do anything besides provide a location and times that could go on the website?

@eeyun, would this be *instead of* or *in addition to* the online video meeting room I'm about to open another issue for?

**Comment by skade** [comment]
Nothing needed beyond that data :). Any comments, leave them here :).

**Comment by eeyun** [comment]
So this would be Instead of the digital location. Trying to see today if I can make this happen. Regarding the online workshop, if I can get it worked out we could have the zoom conference that links directly to our physical conference rooms which might allow for both at the same time?

**Comment by eeyun** [comment]
Ok so it sounds like perhaps the Physical location is _not_ going to work for us. Which means this can be closed. I'll switch over to the issue [here](https://github.com/rust-community/novemb.rs/issues/23)
