### ISSUE TITLE
Workshop location: Online video

### ISSUE THREAD

**Issue by carols10cents** [rust-community/novemb.rs#23]
@eeyun, with Chef/Habitat, is interested in supporting an online video meeting room! @eeyun, would you be able to do this 24 hours a day? How many people would be able to be in the video room? How would signup work?

**Comment by skade** [comment]
Are there any good services for this, maybe related to coding?

**Comment by skade** [comment]
https://screenhero.com/ was a suggestion on twitter.

**Comment by eeyun** [comment]
My apologies it was a busy week last week. So to clarify the physical location would likely be _instead_ of the web location. But I'm trying to get more info on whether this is doable or not. I hope to know by EOD today. 

We have zoom.us Conference rooms that folks could use, screenhero is also solid as is the atom-pair plugin https://atom.io/packages/atom-pair

**Comment by eeyun** [comment]
To answer the other questions: Signup could be done through github with a PR and we could email links out to people that were interested. We likely wouldn't do 24hr sessions (but i'll get clarification on that) and  as far as the number of people, the video conferencing software we use scales quite well but obviously it can be complicated for multiple tracks of conversation to occur digitally like that :)

**Comment by skade** [comment]
@eeyun we could also set up a special IRC channel for people to promote and find people for sessions.
