### ISSUE TITLE
Workshop location: Progressbar hackerspace, Bratislava

### ISSUE THREAD

**Issue by Kixunil** [rust-community/novemb.rs#24]
I will be very happy to host the workshop in Progresssbbar hackerspace. I've already [booked the event](https://www.progressbar.sk/en/calendar/novemb-rs).

Unfortunately, 20 November is already taken, but I'll try to do something about it.

**Comment by skade** [comment]
Thanks, I added you to the page :). I'll add a comment field tomorrow for such additional info.

**Comment by badboy** [comment]
Added information about times

**Comment by Kixunil** [comment]
Sorry, I completely forgotten to update the event. I've found that the other event takes up just one room, so we can take other room. I've added [the info](https://www.progressbar.sk/calendar/novemb-rs--2).

If you need to contact me, e-mail will be probably quicker: martin.habovstiak@gmail.com.

**Comment by badboy** [comment]
Changed the note then!
