### ISSUE TITLE
Workshop location - Karlsruhe

### ISSUE THREAD

**Issue by oli-obk** [rust-community/novemb.rs#28]
I don't have the OK for the location yet, but it looks like I have one for 10 ppl.

I'm going to bring 7 (I'm sure we can share) stm32f7 discovery boards (http://de.rs-online.com/web/p/products/8820278/) and some code to get them running quickly (we do have graphics! and stereo microphone input)

**Comment by badboy** [comment]
Cool! Please let us know you confirm the location so we can add it to the website.

**Comment by japaric** [comment]
> I'm going to bring 7 (I'm sure we can share) stm32f7 discovery boards

nice!

> some code to get them running quickly (we do have graphics! and stereo microphone input)

You meant to say that you got (or will have) Rust programs that make use of the graphics and/or the microphone?

**Comment by oli-obk** [comment]
> You meant to say that you got (or will have) Rust programs that make use of the graphics and/or the microphone?

Well... I personally don't xD but I'll steal @phil-opp 's Rust program that takes the stereo audio and shows it live as squiggly lines on the screen. Should be a good starting point so noone has to grok the setup bit twiggling but can instead dive right into application programming.

**Comment by oli-obk** [comment]
Location kind of depends on the amount of people coming. If we plan for 10 people that's the absolute upper limit. If we plan for more people and fewer come, we might end up sitting in a big room with just a handful people.

**Comment by oli-obk** [comment]
Ok, we have a go:

Location: http://www.openstreetmap.org/search?query=karlsruhe#map=19/49.00668/8.40738

Website: https://entropia.de/Hauptseite

If you are arriving early on Saturday (before noon), bring some rusty food (snacks, stuff to put on bread, ...)

We'll have boards for you to play with at the event.
If you want to take a board home, bring 45 Euros (http://de.rs-online.com/web/p/products/8820278/).

Note: we only have space for 10 laptops. We can probably fit more people, but that's it.

**Comment by skade** [comment]
@oli-obk would you like to have access to the Rust Karlsruhe meetup-Account by the way?

**Comment by oli-obk** [comment]
There is such a thing? Sure.

**Comment by skade** [comment]
@oli-obk sure, there was a Rust Hack & Learn for a while.

Please send me a message there from your users account: http://www.meetup.com/Rust-Hack-Learn-Karlsruhe

**Comment by badboy** [comment]
Added Karlsruhe to the website
