### ISSUE TITLE
Workshop in Paris?

### ISSUE THREAD

**Issue by erickt** [rust-community/novemb.rs#30]
There's a hunt going on for a space to host a novemb.rs event in Paris. According to @pnkfelix, the Mozilla Paris office is unavailable. @jedisct1, any chance there's space in OVH we could use?

**Comment by skade** [comment]
snips.ai (/cc @kali) would like to host us.

Possible time frame: 14h-21h on sat, 14h-19h on sunday.

@pnkfelix, @simonsapin, can any of you help out there?

**Comment by SimonSapin** [comment]
I won’t be in Paris on Nov. 19 / 20, sorry.

**Comment by pnkfelix** [comment]
I can be there for part of each day, but not the whole time frame listed.

In particular, I can attend starting at 14h (or a little earlier, but not much) on both days, but probably cannot stay past 17h on either day.

**Comment by GuillaumeGomez** [comment]
Same as @pnkfelix. I can be there, but not all the time (not morning mainly).

EDIT: apparently the event isn't in the morning so no problem. :)

**Comment by kali** [comment]
All right, sounds good. I'll cover the whole range of opening hours from the room+wifi+chairs+tables(+whatever) point of view.

Having Felix at the start of each day, plus Guillaume around to help sounds good.

We may or may not have refreshment and/or foods courtesy of the mozilla office in Paris, this is being enquired by @pnkfelix, but this is probably not a blocking issue considering the planned opening hours.

Our basement room have a few idiosyncrasies that we may want to warn people about: first, it is very non-wheelchair accessible. To be clear, even accessing the building door would be greatly challenging. Secondly, the space is very hard to heat, so even in november it is relatively fresh.

What's next ?

**Comment by pnkfelix** [comment]
FYI Mozilla will pay for pizzas both Saturday and Sunday.
