### ISSUE TITLE
Workshop location: Cambridge UK

### ISSUE THREAD

**Issue by thejpster** [rust-community/novemb.rs#5]
I think we should meet in Cambridge, UK. Mainly because that's where I work, but also because it's got a huge tech cluster.

**Comment by skade** [comment]
Have you got news on this? Were you able to find a space?

**Comment by jgouly** [comment]
Maybe interested!

**Comment by thejpster** [comment]
No, I'm afraid I haven't had the time to arrange a space we can make
publicly available. But I'm sure there must be somewhere out there!

**Comment by skade** [comment]
A friend of mine suggests talking to the uni https://twitter.com/myabc/status/795997601443287041 or ARM Community: https://twitter.com/myabc/status/795997954310045696

**Comment by thejpster** [comment]
The Cambridge Raspberry Jam uses the Institute of Astronomy. I'll ask
@recantha.

**Comment by thejpster** [comment]
I've pinged the IoA. I'm also asking @cambridgeconsultants and I'll try a contact at ARM. Any other ideas? Anyone know anyone in the CS department?

**Comment by skade** [comment]
Another suggestion from Twitter mentioned: http://makespace.org/ they hosted the "good for nothing" hack event.

**Comment by japaric** [comment]
(cc @parched who's in Cambridge)

**Comment by parched** [comment]
Hi guys, I'll also have a think about this. How many people are we likely to have?

**Comment by skade** [comment]
@parched I wouldn't expect too many... 10 tops, maybe more if it's successful?

**Comment by parched** [comment]
I asked at my work (ARM) about using one of the rooms and there is a bit of paperwork involved including a full list of attendees and times we would be there. Do we want to proceed with that?

We could probably just go to a cafe or pub if there is only a few of us. Worst case scenario, I have 2 chairs and 2 stools around the 1 metre square table in my house :smile:.

**Comment by thejpster** [comment]
I asked a friend at ARM and got a similar answer.

Café/pub could work, if we weren't there too long (or spent enough). Would
be nice to put faces to names if nothing else.

Do they have WiFi in the Grafton Centre? If so, how about the food court
upstairs by the cinema, at, say 10am on Saturday?

**Comment by thejpster** [comment]
Actually, hold that thought - something's come up and I might be able to go one better. I'll let you know by tomorrow.

**Comment by thejpster** [comment]
OK, I have a tentative result at a venue on the Cambridge Science Park (to the north of Cambridge city centre, by the A14/A10 junction). There is still a chance it might be declined, but, if it goes ahead I'm going to need names in advance. Let's assume a 10am start and we'll probably be done by 4pm (sorry, I've got other things going on in the evening and guests must be escorted). There is no vending, so please bring snacks and drinks, or walk to the Golden Lion Public House or Tesco Supermarket nearby. We do have WiFi, power and parking.

As I said, this is still TBD, but if you are interested, comment here or otherwise send me your name, e-mail address and contact number and I will provisionally book you in. I cannot let you in on-spec, so please do not guess the venue and/or turn up without booking. If it all falls through, we'll just go to a pub as suggested above.

Either way, can we get Cambridge listed on the novemb.rs page?

Thanks!

**Comment by badboy** [comment]
Sure! Full pre-signup sounds less optimal, but if it works out great. 
You can add yourself here: https://github.com/rust-community/novemb.rs/blob/gh-pages/_data/locations.yml
At best a map link and a note about signing up in this issue would be necessary

**Comment by thejpster** [comment]
Event approved and pull request sent.

Cambridge Consultants, Cambridge, UK
http://www.openstreetmap.org/?mlat=52.23235&mlon=0.14390#map=19/52.23235/0.14390
Open Saturday 10am-4pm. Please note, you MUST contact novembrs@thejpster.org.uk or comment here before arriving.

**Comment by thejpster** [comment]
I just wanted to say I really enjoyed today, and I hope those of you carrying on tomorrow have a great day.
